apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRole
metadata:
  name: reviews-viewer
  namespace: default
spec:
  rules:
  - services: ["reviews.default.svc.cluster.local"]
    methods: ["GET"]
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: bind-reviews-viewer
  namespace: default
spec:
  subjects:
  - user: "*"
  roleRef:
    kind: ServiceRole
    name: reviews-viewer
